root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
rules:
  quotes:
    - error
    - single
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/ban-ts-comment":
    - "error"
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
      ts-nocheck: true
      ts-check: false
      minimumDescriptionLength: 5
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/consistent-type-imports":
    - error
    - prefer: type-imports
      disallowTypeAnnotations: true
      fixStyle: inline-type-imports
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  simple-import-sort/imports:
    - error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  import/no-restricted-paths:
    - error
    - zones:
        # imports with 'from #server/' allowed only for lib code inside server/ dir
        - target: "./src/lib/!(server)/**/*"
          from: "./src/lib/server"
        # #shared code can't import code 'from #client'/'from #server'
        - target: "./src/lib/shared"
          from: ["./src/lib/server", "./src/lib/client"]
        # src code can't import code 'from #tests/'
        - target: "./src"
          from: ["./tests"]
        # code can't import code 'from #client/hooks/*', use index.ts exports
        - target: "./src/lib/client/!(hooks)/**/*"
          from: ["./src/lib/client/hooks/!(index.ts)"]
        # code can't import code 'from #shared/utils/*', use index.ts exports
        - target: "./src/lib/shared/!(utils)/**/*"
          from: ["./src/lib/shared/utils/!(index.ts)"]
settings:
  import/resolver:
    # You will also need to install and configure the TypeScript resolver
    # See also https://github.com/import-js/eslint-import-resolver-typescript#configuration
    typescript: true
    node: true
parserOptions:
  sourceType: module
env:
  browser: true
  es2022: true
  node: true
overrides:
  # build-time files
  - files:
      - "build/**/*.{ts,tsx}"
      - "src/lib/server/**/*.{ts,tsx}"
      - "src/**/*.server.{ts,tsx}"
      - "tests/**/*.{ts,tsx}"
      - "./*.{ts,mjs,js,cjs}"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
