root: true
parser: "@typescript-eslint/parser"
plugins:
  - svelte3
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/ban-ts-comment": "off"
  quotes:
    - error
    - single
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
      packageDir: [., ./src/lib/server, ./src/lib/build-time]
  import/no-restricted-paths:
    - error
    - zones:
        - target:
            - ./src/!(server)/**/*
            - ./src/!(build-time)/**/*
          from:
            - ./src/lib/server
            - ./src/lib/build-time
overrides:
  - files:
      - "*.svelte"
    processor: svelte3/svelte3
settings:
  svelte3/typescript: true
parserOptions:
  sourceType: module
env:
  browser: true
  es2022: true
  node: true
