root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - simple-import-sort
  - unicorn
  - solid
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - plugin:solid/typescript
rules:
  quotes:
    - error
    - single
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/ban-ts-comment":
    - "error"
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
      ts-nocheck: true
      ts-check: false
      minimumDescriptionLength: 5
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/consistent-type-imports":
    - error
    - prefer: type-imports
      disallowTypeAnnotations: true
      fixStyle: inline-type-imports
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
  # MUCH slower
  unicorn/prefer-query-selector: "off"
  # dataset is much slower than attributes
  # https://www.measurethat.net/Benchmarks/Show/14432/0/getattribute-vs-dataset#latest_results_block
  unicorn/prefer-dom-node-dataset: "off"
  # conflicts with vscode default formatter
  unicorn/empty-brace-spaces: "off"
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/prevent-abbreviations:
    - error
    - extendDefaultReplacements: false
      replacements:
        cmd:
          command: true
        e:
          event: true

  simple-import-sort/imports:
    - error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  import/no-restricted-paths:
    - error
    - zones:
        - message: non-server code can't refer to the server code
          from: ./src/lib/server
          target: ./src/lib/!(server)/**/*

        - message: shared code can't refer to client or server code
          from: ["./src/lib/server", "./src/lib/client"]
          target: ./src/lib/shared

        - message: code can't refer to tests code
          from: ["./tests"]
          target: "./src"

        - message: "can't import code 'from #client/hooks/*' directly, use index.ts exports"
          from: ["./src/lib/client/hooks/!(index).{ts,tsx}"]
          target: "./src/lib/client/!(hooks)/**/*"

        - message: "can't import code 'from #shared/utils/*' directly, use index.ts exports"
          from: ["./src/lib/*/utils/!(index.ts)"]
          target: "./src/lib/*/!(utils)/**/*"

        - message: "can't import internal code, use index.ts exports first"
          from: "./src/lib/**/*.internal.{tsx,ts}"
          target: ["./src/lib/**/!(index).{ts,tsx}"]

settings:
  import/resolver:
    # You will also need to install and configure the TypeScript resolver
    # See also https://github.com/import-js/eslint-import-resolver-typescript#configuration
    typescript: true
    node: true
parserOptions:
  sourceType: module
env:
  browser: true
  es2022: true
  node: true
overrides:
  # build-time files
  - files:
      - "build/**/*.{ts,tsx}"
      - "src/lib/server/**/*.{ts,tsx}"
      - "src/**/*.server.{ts,tsx}"
      - "tests/**/*.{ts,tsx}"
      - "./*.{ts,mjs,js,cjs}"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
