// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	site_title: string
	/**
	 * H​o​m​e​p​a​g​e​ ​o​f​ ​V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	meta_description: string
	/**
	 * V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	author: string
	/**
	 * S​e​a​r​c​h
	 */
	search: string
	/**
	 * I​n​d​e​x
	 */
	index: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * N​o​t​ ​f​o​u​n​d
	 */
	not_found: string
	/**
	 * L​o​a​d​i​n​g
	 */
	loading: string
	/**
	 * U​n​k​n​o​w​n​ ​e​r​r​o​r
	 */
	error_unknown: string
	/**
	 * E​r​r​o​r​ ​i​n​f​o​r​m​a​t​i​o​n
	 */
	error_info: string
	/**
	 * T​r​y​ ​a​g​a​i​n
	 */
	try_again: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * s​c​o​r​e
	 */
	stork_score: string
	/**
	 * N​O​T​ ​F​O​U​N​D
	 */
	stork_not_found: string
	/**
	 * T​y​p​e​ ​a​ ​q​u​e​r​y​ ​i​n​t​o​ ​t​h​e​ ​i​n​p​u​t
	 */
	stork_empty_query: string
	/**
	 * O​l​d​e​r​ ​p​o​s​t​s​ ​→
	 */
	posts_next: string
	/**
	 * ←​ ​N​e​w​e​r​ ​p​o​s​t​s
	 */
	posts_previous: string
	/**
	 * P​a​g​e
	 */
	page: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	hello: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​[​e​n​]​ ​{​f​i​l​e​N​a​m​e​}
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
}

export type TranslationFunctions = {
	/**
	 * Vladimir Chirikov
	 */
	site_title: () => LocalizedString
	/**
	 * Homepage of Vladimir Chirikov
	 */
	meta_description: () => LocalizedString
	/**
	 * Vladimir Chirikov
	 */
	author: () => LocalizedString
	/**
	 * Search
	 */
	search: () => LocalizedString
	/**
	 * Index
	 */
	index: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Not found
	 */
	not_found: () => LocalizedString
	/**
	 * Loading
	 */
	loading: () => LocalizedString
	/**
	 * Unknown error
	 */
	error_unknown: () => LocalizedString
	/**
	 * Error information
	 */
	error_info: () => LocalizedString
	/**
	 * Try again
	 */
	try_again: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * score
	 */
	stork_score: () => LocalizedString
	/**
	 * NOT FOUND
	 */
	stork_not_found: () => LocalizedString
	/**
	 * Type a query into the input
	 */
	stork_empty_query: () => LocalizedString
	/**
	 * Older posts →
	 */
	posts_next: () => LocalizedString
	/**
	 * ← Newer posts
	 */
	posts_previous: () => LocalizedString
	/**
	 * Page
	 */
	page: () => LocalizedString
	/**
	 * Hello {name}
	 */
	hello: (arg: { name: string }) => LocalizedString
	/**
	 * This log was called from [en] {fileName}
	 */
	log: (arg: { fileName: string }) => LocalizedString
}

export type Formatters = {}
