// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}
	 * @param {unknown} name
	 */
	hello: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​[​e​n​]​ ​{​f​i​l​e​N​a​m​e​}
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
}

export type TranslationFunctions = {
	/**
	 * Hello {name}
	 */
	hello: (arg: { name: unknown }) => LocalizedString
	/**
	 * This log was called from [en] {fileName}
	 */
	log: (arg: { fileName: string }) => LocalizedString
}

export type Formatters = {}
