// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	site_title: string
	/**
	 * H​o​m​e​p​a​g​e​ ​o​f​ ​V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	meta_description: string
	/**
	 * V​l​a​d​i​m​i​r​ ​C​h​i​r​i​k​o​v
	 */
	author: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	hello: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​[​e​n​]​ ​{​f​i​l​e​N​a​m​e​}
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
}

export type TranslationFunctions = {
	/**
	 * Vladimir Chirikov
	 */
	site_title: () => LocalizedString
	/**
	 * Homepage of Vladimir Chirikov
	 */
	meta_description: () => LocalizedString
	/**
	 * Vladimir Chirikov
	 */
	author: () => LocalizedString
	/**
	 * Hello {name}
	 */
	hello: (arg: { name: string }) => LocalizedString
	/**
	 * This log was called from [en] {fileName}
	 */
	log: (arg: { fileName: string }) => LocalizedString
}

export type Formatters = {}
